apiVersion: v1
kind: Secret
metadata:
  name: purview-secret
  namespace: purview
type: Opaque
stringData:
  PURVIEW_NAME: "your--purview--account"
  AZURE_CLIENT_ID: "your--client--id"
  AZURE_CLIENT_SECRET: "your--client--secret"
  AZURE_TENANT_ID: "your--tenant"
